GET http://localhost:8080/screenshots/0MaOaM0Q1vKnYRUY.png

###

GET http://localhost:8080/api/screenshot?url=https%3A%2F%2Fir3.xyz%2F5ad05d9dbeb84

###

GET http://localhost:8080/api/trace?url=https%3A%2F%2Fir3.xyz%2F5ad05d9dbeb84

###

GET http://localhost:8080/api/trace?url=http%3A%2F%2Fssyoutube.com

###

GET http://localhost:8080/api/find/5f8adea94e8ee443e33036c8

###

GET http://api.redirective.net/api/trace/chrome?url=http%3A%2F%2Fssyoutube.com

###

GET http://api.redirective.net/api/trace/chrome?url=https%3A%2F%2Fir3.xyz%2F5ad05d9dbeb84

###