version: '3.5'

services:
  redirective:
    image: redirective-scratch:latest
    env_file :
      - ./.env
    volumes:
      - ./logs:${LOG_PATH}
    ports:
    - 8080:8080
    depends_on:
      - mongo
      - chrome
    links:
      - mongo
      - chrome

  chrome:
    hostname: chrome
    image: mkenney/chromium-headless:latest
    ports:
      - 9222:9222
    entrypoint: sh
    command:
      - "-cexu"
      - "/usr/bin/google-chrome --addr=localhost --port=9222 --remote-debugging-port=9222 --remote-debugging-address=0.0.0.0 --disable-extensions --disable-gpu --headless --hide-scrollbars --no-first-run --no-sandbox"

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - mongo-storage:/data/db

volumes:
  mongo-storage:
